language: c

addons:
    apt:
        packages:
            - elfutils
            - zlib1g-dev

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"
    exclude:
        - os: osx
          compiler: gcc

script:
    - ./autogen.sh
    - ./configure
    - make
    - make test
